---
# Run it with:
#   ap labs/multiarch/deploy.yaml

- name: 'Clean multiarch lab'
  ansible.builtin.import_playbook: ../../playbooks/jobs/clean-lab.yml
  vars:
    lab_name: 'multiarch'
  tags:
    - 'clean'
    - 'never'

- name: 'Import ABI playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  tags:
    - 'ocp'
  vars:
    lab_name: 'multiarch'
    lab_abi_ip: "{{ lab_node_network_base }}61"
    lab_api_ips: ["{{ lab_node_network_base }}100"]
    lab_ingress_ips: ["{{ lab_node_network_base }}101"]
    lab_node_memory: 28000
    lab_node_disk_data: 60
    lab_hosts:
      - {id: '61', role: 'master'}
      - {id: '62', role: 'master'}
      - {id: '63', role: 'master'}
    start_install: true

- name: 'Install ACM on hub cluster'
  ansible.builtin.import_playbook: ../../playbooks/setup/hive.yml
  tags:
    - 'postinst'
    - 'acm'
  vars:
    lab_name: 'multiarch'

    ocp_assisted_service_op: 'acm'
    ocp_assisted_service_images:
      - ocp_version: '4.18.1'
        arch: 'x86_64'
        version: '418.94.202501221327-0'
      - ocp_version: '4.18.1'
        arch: 'arm64'
        version: '418.94.202501221327-0'
    ocp_assisted_service_infraenvs:
      - name: "spoke-{{ lab_name }}"
        ns: 'managed'
        ntp: ["{{ lab_node_network_base }}1"]
        redfish: "{{ lab_node_network_base }}1"
        inventory:
          - {'name': "{{ lab_name }}-bmh-1", 'id': '64'}
          - {'name': "{{ lab_name }}-bmh-2", 'id': '65'}
          - {'name': "{{ lab_name }}-bmh-3", 'id': '66'}

    ocp_hive_clusters:
      - name: "spoke-{{ lab_name }}"
        ns: 'managed'
        image: 'img4.18.6-multi-appsub'
        service_network: '172.32.0.0/16'
        host_network: "{{ lab_node_network_base }}0/24"
        masters: 3
        domain: 'local.lab'
        api_vips: ["{{ lab_node_network_base }}102"]
        ingress_vips: ["{{ lab_node_network_base }}103"]

- name: 'Extract spoke cluster configuration'
  ansible.builtin.import_playbook: ../../playbooks/jobs/hive-config.yml
  vars:
    lab_name: 'multiarch'
    lab_path: '/root/labs'
    hive_cluster_name: "spoke-{{ lab_name }}"
    hive_ns: 'managed'
  tags:
    - 'postinst'
    - 'hive-config'

- name: 'Import cluster spoke-multiarch'
  ansible.builtin.import_playbook: ../../playbooks/jobs/acm-import-cluster.yaml
  vars:
    lab_name: 'multiarch'
    cluster_name: 'spoke-multiarch'
    kubeconfig_path: '/root/labs/multiarch/spoke-multiarch/auth/kubeconfig'
  tags:
    - 'postinst'
    - 'import-cluster'
