---
- name: 'Install container engine'
  ansible.builtin.package:
    name: "{{ kind_container_engine }}"
    state: 'present'
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - 'packages'

- name: 'Download kind'
  ansible.builtin.get_url:
    url: "https://kind.sigs.k8s.io/dl/v{{ kind_version }}/kind-linux-amd64"
    dest: "/usr/local/bin/kind"
    owner: 'root'
    group: 'root'
    mode: '0755'
    force: "{{ kind_reinstall }}"

- name: 'Create kind configuration directory'
  ansible.builtin.file:
    path: "{{ kind_cfg_dir }}"
    state: directory

- name: 'Increase inotify max_user_watches'
  ansible.posix.sysctl:
    name: 'fs.inotify.max_user_watches'
    value: 524288
    state: present
    sysctl_file: '/etc/sysctl.d/95-inotify-max_user_watches.conf'
    sysctl_set: True
    reload: True

- name: 'Increase inotify max_user_instances'
  ansible.posix.sysctl:
    name: 'fs.inotify.max_user_instances'
    value: 512
    state: present
    sysctl_file: '/etc/sysctl.d/95-inotify-max_user_instances.conf'
    sysctl_set: True
    reload: True

- name: 'Create kind clusters'
  ansible.builtin.include_tasks: clusters.yaml
  loop: "{{ kind_clusters }}"
...
