---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-network
  namespace: metallb-system
spec:
  autoAssign: true
  addresses:
    - 192.168.125.62-192.168.125.64
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertise-lab-network
  namespace: metallb-system
spec:
  ipAddressPools:
    - lab-network
