---
galaxy_info:
  role_name: ocp_vpo
  namespace: mlorenzofr
  author: 'Manuel Lorenzo'
  description: 'Install and configure Validated Patterns Operator (VPO) on an Openshift Cluster'
  company: 'Red Hat'
  license: 'MIT'
  min_ansible_version: '2.12'
  platforms:
    - name: 'EL'
      versions:
        - '8'
        - '9'
  galaxy_tags: []
dependencies: []
