---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    visible: "true"
  name: okd-4.15.0-x86-64-20240118223523
spec:
  releaseImage: registry.ci.openshift.org/origin/release-scos:4.15.0-0.okd-scos-2024-01-18-223523
