---
- name: 'Make cluster image visible'
  kubernetes.core.k8s:
    definition:
      apiVersion: 'hive.openshift.io/v1'
      kind: 'ClusterImageSet'
      metadata:
        name: "{{ item.image }}"
        labels:
          visible: 'true'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Create dnsmasq snippet for the cluster nodes'
  ansible.builtin.include_role:
    name: 'dnsmasq'
    tasks_from: 'extra_conf.yaml'
  vars:
    dnsmasq_conf_snippets:
      - {src: 'dnsmasq-hive.j2', dest: "{{ ocp_hive_lab_name }}-{{ item.name }}-cluster.conf"}
  tags: ['dnsmasq']

- name: 'Prepare hive cluster'
  ansible.builtin.template:
    src: 'cluster.yaml.j2'
    dest: "{{ ocp_hive_path }}/hive/{{ item.name }}.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Apply hive cluster manifest'
  kubernetes.core.k8s:
    state: 'present'
    src: "{{ ocp_hive_path }}/hive/{{ item.name }}.yaml"
  ignore_errors: "{{ ansible_check_mode }}"
  when: ocp_hive_apply
...
