---
- name: 'Check image visibility'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc get clusterimageset {{ item.image }} -o jsonpath='{.metadata.labels.visible}'
  register: __hive_image_visibility
  changed_when: false
  failed_when: false

- name: 'Make cluster image visible'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc label clusterimageset {{ item.image }} visible=true --overwrite
  when: __hive_image_visibility.stdout == 'false'

- name: 'Create dnsmasq snippet for the cluster nodes'
  ansible.builtin.include_role:
    name: 'dnsmasq'
    tasks_from: 'extra_conf.yaml'
  vars:
    dnsmasq_conf_snippets:
      - {src: 'dnsmasq-hive.j2', dest: "{{ ocp_hive_lab_name }}-{{ item.name }}-cluster.conf"}
  tags: ['dnsmasq']

- name: 'Prepare hive cluster'
  ansible.builtin.template:
    src: 'cluster.yaml.j2'
    dest: "{{ ocp_hive_path }}/hive/{{ item.name }}.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
  notify: 'hive cluster update'
...
