---
- name: 'Make cluster image visible'
  kubernetes.core.k8s:
    definition:
      apiVersion: 'hive.openshift.io/v1'
      kind: 'ClusterImageSet'
      metadata:
        name: "{{ item.image }}"
        labels:
          visible: 'true'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Create dnsmasq snippet for the cluster nodes'
  ansible.builtin.include_role:
    name: 'dnsmasq'
    tasks_from: 'extra_conf.yaml'
  vars:
    dnsmasq_conf_snippets:
      - {src: 'dnsmasq-hive.j2', dest: "{{ ocp_hive_lab_name }}-{{ item.name }}-cluster.conf"}
  tags: ['dnsmasq']

- name: 'Create hive cluster namespace'
  kubernetes.core.k8s:
    name: "{{ item.ns }}"
    api_version: v1
    kind: Namespace
    state: present

- name: 'Create hive cluster pull-secret'
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: 'v1'
      kind: 'Secret'
      type: 'kubernetes.io/dockerconfigjson'
      metadata:
        name: "pullsecret-cluster-{{ item.name }}"
        namespace: "{{ item.ns }}"
      data:
        .dockerconfigjson: "{{ item.pullsecret | default(ocp_hive_pullsecret) }}"

- name: 'Prepare hive cluster'
  ansible.builtin.template:
    src: 'cluster.yaml.j2'
    dest: "{{ ocp_hive_path }}/hive/{{ item.name }}.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Apply hive cluster manifest'
  kubernetes.core.k8s:
    state: 'present'
    src: "{{ ocp_hive_path }}/hive/{{ item.name }}.yaml"
  ignore_errors: "{{ ansible_check_mode }}"
  when: ocp_hive_apply
...
