---
- name: 'Install Hive operator'
  ansible.builtin.template:
    src: 'subscription.j2'
    dest: "{{ ocp_hive_path }}/hive-subscription.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
  when: ocp_hive_operator
  notify: 'hive operator install'

- name: 'Create cluster configurations directory'
  ansible.builtin.file:
    path: "{{ ocp_hive_path }}/hive"
    mode: '0750'
    state: 'directory'

- name: 'Create custom ClusterImageSets'
  ansible.builtin.template:
    src: 'clusterimageset.yaml.j2'
    dest: "{{ ocp_hive_path }}/clusterimageset.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
  when: ocp_hive_clusterimagesets | length > 0
  notify: 'hive clusterimagesets'

- name: 'Prepare hive clusters'
  ansible.builtin.include_tasks:
    file: 'cluster.yml'
  loop: "{{ ocp_hive_clusters }}"
...
