---
- name: 'Create hive subscription manifest'
  ansible.builtin.include_role:
    name: 'ocp_olm'
    tasks_from: 'subscription.yaml'
  loop:
    - operator_name: 'hive-operator'
      ns: "{{ ocp_hive_ns }}"
      channel: "{{ ocp_hive_channel }}"
      source: "{{ ocp_hive_source }}"
  when: ocp_hive_operator
  tags: ['olm']

- name: 'Waiting for hive-operator pods'
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        namespace: "{{ ocp_hive_ns }}"
    label_selectors:
      - 'control-plane=hive-operator'
    wait: yes
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Create cluster configurations directory'
  ansible.builtin.file:
    path: "{{ ocp_hive_path }}/hive"
    mode: '0750'
    state: 'directory'

- name: 'Create custom ClusterImageSets'
  ansible.builtin.template:
    src: 'clusterimageset.yaml.j2'
    dest: "{{ ocp_hive_path }}/clusterimageset.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
  when: ocp_hive_clusterimagesets | length > 0

- name: 'Apply ClusterImageSet manifest'
  kubernetes.core.k8s:
    state: 'present'
    src: "{{ ocp_hive_path }}/clusterimageset.yaml"
  ignore_errors: "{{ ansible_check_mode }}"
  when: ocp_hive_clusterimagesets | length > 0 and ocp_hive_apply

- name: 'Prepare hive clusters'
  ansible.builtin.include_tasks:
    file: 'cluster.yml'
  loop: "{{ ocp_hive_clusters }}"
...
