---
- name: 'Set installation type to ABI'
  ansible.builtin.set_fact:
    lab_abi: True
  check_mode: no

- name: 'Include ocp_appliance role'
  ansible.builtin.include_role:
    name: 'ocp_appliance'

- name: 'Prepare VMs disks (appliance)'
  ansible.builtin.set_fact:
    __lab_vm_disks: []
