---
apiVersion: v1
metadata:
  name: cnv
baseDomain: local.lab
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: fd00:0:0:1::/64
  clusterNetwork:
    - cidr: fd01::/48
      hostPrefix: 64
  serviceNetwork:
    - fd02::/112
additionalTrustBundlePolicy: Proxyonly
proxy:
  httpProxy: http://[fd00:0:0:1::1]:3128
  httpsProxy: http://[fd00:0:0:1::1]:3128
  noProxy: cnv.local.lab,api-int.cnv.local.lab,fd00:0:0:1::/64,fd01::/48,fd02::/112
compute:
  - name: worker
    architecture: amd64
    hyperthreading: Enabled
    replicas: 3
controlPlane:
  name: master
  architecture: amd64
  hyperthreading: Enabled
  replicas: 3
platform:
  baremetal:
    apiVIPs: ['fd00:0:0:1::10']
    ingressVIPs: ['fd00:0:0:1::11']
    externalMACAddress: be:be:ca:fe:06:00
    provisioningNetwork: Disabled
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
