apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs1
  namespace: openshift-storage-odf
spec:
  manageNodes: false
  resources:
    mds:
      limits:
        cpu: "3"
        memory: "8Gi"
      requests:
        cpu: "3"
        memory: "8Gi"
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
    - count: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "150Gi"
          storageClassName: localblock
          volumeMode: Block
      name: deviceset1
      placement: {}
      portable: false
      replica: 3
