---
apiVersion: v1
kind: Namespace
metadata:
  name: hive-sno
---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret-infra1
  namespace: hive-sno
stringData:
  .dockerconfigjson: '{"auths":{<redacted>}}'
type: kubernetes.io/dockerconfigjson
---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: infra1
  namespace: hive-sno
spec:
  additionalNTPSources:
    - 192.168.125.1
  clusterRef:
    name: sno
    namespace: hive-sno
  agentLabels:
    cluster-name: "sno"
  pullSecretRef:
    name: pull-secret-infra1
  sshAuthorizedKey: <redacted>
