---
apiVersion: v1
baseDomain: manor.lab
networking:
  networkType: OVNKubernetes
  machineCIDR: 192.168.128.0/24
  clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
metadata:
  name: dan
compute:
  - name: worker
    architecture: amd64
    hyperthreading: Enabled
    replicas: 0
controlPlane:
  name: master
  architecture: amd64
  hyperthreading: Enabled
  replicas: 3
platform:
  baremetal:
    externalBridge: "dan-network"
    provisioningNetwork: "Disabled"
    externalMACAddress: da:00:00:00:00:00
    apiVIPs: ['192.168.128.10']
    ingressVIPs: ['192.168.128.11']
    hosts:
      - name: dan-master-1
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.128.1:9000/redfish/v1/Systems/local/dan-master-1
          username: <redacted>
          password: <redacted>
          disableCertificateVerification: True
        bootMACAddress: da:00:00:00:00:01
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: dan-master-2
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.128.1:9000/redfish/v1/Systems/local/dan-master-2
          username: <redacted>
          password: <redacted>
          disableCertificateVerification: True
        bootMACAddress: da:00:00:00:00:02
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: dan-master-3
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.128.1:9000/redfish/v1/Systems/local/dan-master-3
          username: <redacted>
          password: <redacted>
          disableCertificateVerification: True
        bootMACAddress: da:00:00:00:00:03
        rootDeviceHints:
          deviceName: "/dev/vda"
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
