---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: openshift-operators
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dan-network
  namespace: openshift-operators
spec:
  autoAssign: true
  addresses:
    - 192.168.128.40-192.168.128.45
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertise-dan-network
  namespace: openshift-operators
spec:
  ipAddressPools:
  - dan-network
