---
# Run it with:
#   ap labs/pinned-image-set/deploy.yaml

- name: 'Clean pinned-image-set lab'
  ansible.builtin.import_playbook: ../../playbooks/jobs/clean-lab.yml
  vars:
    lab_name: 'pinnedis'
  tags:
    - 'clean'
    - 'never'

- name: 'Import ABI playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  tags:
    - 'ocp'
  vars:
    lab_name: 'pinnedis'
    lab_abi_ip: "{{ lab_node_network_base }}21"
    lab_api_ips: ["{{ lab_node_network_base }}10"]
    lab_ingress_ips: ["{{ lab_node_network_base }}11"]
    lab_mac_base: 'be:be:ca:fe:04:'
    lab_worker_replicas: 0
    lab_node_network_base: '192.168.129.'
    lab_network_name: 'pinnedis-net'
    lab_node_memory: 22000
    lab_hosts:
      - {id: '21'}
      - {id: '22'}
      - {id: '23'}
    lab_custom_capability_set: 'None'
    lab_custom_capabilities:
      - baremetal
      - MachineAPI
      - marketplace
      - OperatorLifecycleManager
      - Console
      - Ingress
      - Insights
      - Storage
      - CSISnapshot
      - NodeTuning
      - ImageRegistry
      - Build
      - CloudCredential
      - DeploymentConfig
      - CloudControllerManager
    start_install: true

- name: 'Configure Openshift cluster'
  hosts:
    - 'lab'
  gather_facts: false
  vars:
    lab_install: true
    lab_name: 'pinnedis'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    ocp_mco_icsp:
      - name: 'generic-0'
        repo_mirrors:
          - source: 'quay.io/openshift-release-dev/ocp-release:4.17.0-x86_64'
            mirrors:
              - 'pinnedis-registry.pinnedis.local.lab/openshift/release'
          - source: 'registry.access.redhat.com/ubi8'
            mirrors:
              - 'pinnedis-registry.pinnedis.local.lab/ubi8'
      - name: 'release-0'
        repo_mirrors:
          - source: 'quay.io/openshift-release-dev/ocp-v4.0-art-dev'
            mirrors:
              - 'pinnedis-registry.pinnedis.local.lab/openshift/release'
          - source: 'quay.io/openshift-release-dev/ocp-release'
            mirrors:
              - 'pinnedis-registry.pinnedis.local.lab/openshift/release-images'
          - source: 'registry.ci.openshift.org/ocp/release'
            mirrors:
              - 'pinnedis-registry.pinnedis.local.lab/openshift/release-images'
  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"
  roles:
    - 'ocp_mco'
  tags:
    - 'postinst'
    - 'ocp-config'
