apiVersion: v1
kind: Namespace
metadata:
  name: openshift-acm
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-acm-operatorgroup
  namespace: openshift-acm
spec:
  targetNamespaces:
    - openshift-acm
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator
  namespace: openshift-acm
spec:
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: rh-osbs
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Secret
metadata:
  name: acm-pull-secret
  namespace: openshift-acm
data:
  .dockerconfigjson: '{"auths":{<redacted>}}'
type: kubernetes.io/dockerconfigjson
