---
apiVersion: v1
kind: Namespace
metadata:
  name: 'dgonspk'
  # labels:
  #  cluster.open-cluster-management.io/managedCluster: 'dgonspk'
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: 'dgonspk'
spec:
  hubAcceptsClient: true
---
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: 'dgonspk'
type: Opaque
stringData:
  autoImportRetry: "5"
  kubeconfig: |-
    clusters:
    - cluster:
        certificate-authority-data: <redacted>
        server: https://api.dgonspk.local.lab:6443
      name: dgonspk
    contexts:
    - context:
        cluster: dgonspk
        user: admin
      name: admin
    current-context: admin
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: <redacted>
        client-key-data: <redacted>
