---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: lmproxy
rendezvousIP: 192.168.129.21
hosts:
  - hostname: lmproxy-node-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:06:21
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:06:21
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: lmproxy-node-2
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:06:22
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:06:22
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: lmproxy-node-3
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:06:23
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:06:23
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
