---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: stdslim
rendezvousIP: 192.168.125.51
hosts:
  - hostname: stdslim-node-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:05:51
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:05:51
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: stdslim-node-2
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:05:52
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:05:52
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: stdslim-node-3
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:05:53
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:05:53
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
