---
# This playbook installs a lab with an Openshift Cluster with IPv6 Single Stack
#
# Run it with:
#   ap labs/cnv-ipv6/deploy.yaml

- name: 'Import ABI playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  tags:
    - 'ocp'
  vars:
    lab_abi_ip: "{{ lab_node_network_base }}21"
    lab_api_ips: ["{{ lab_node_network_base }}10"]
    lab_bootstrap_ip: "[::100]"
    lab_dns_servers: ["{{ lab_node_network_base }}1"]
    lab_ntp_sources: ["{{ lab_node_network_base }}1"]
    lab_gateway: "{{ lab_node_network_base }}1"
    lab_ingress_ips: ["{{ lab_node_network_base }}11"]
    lab_name: 'cnv'
    lab_mac_base: 'be:be:ca:fe:06:'
    lab_worker_replicas: 3
    lab_node_ipv4: false
    lab_node_ipv6: true
    lab_node_memory: 33000
    lab_node_network: "{{ lab_node_network_base }}/64"
    lab_node_network_base: 'fd00:0:0:1::'
    lab_cluster_network: 'fd01::/48'
    lab_cluster_network_prefix: 64
    lab_service_network: 'fd02::/112'
    lab_proxy_http: "http://[{{ lab_node_network_base }}1]:3128"
    lab_network_name: 'cnv-ipv6'
    lab_hosts:
      - {id: '21'}
      - {id: '22'}
      - {id: '23'}
      - {id: '24'}
      - {id: '25'}
      - {id: '26'}
    start_install: true

- name: 'Setup Openshift Data Foundation (ODF)'
  ansible.builtin.import_playbook: ../../playbooks/setup/odf.yaml
  tags:
    - 'postinst'
    - 'odf'
  vars:
    lab_name: 'cnv'
    ocp_localstorage_nodes:
      - {'name': "{{ lab_name }}-node-4", 'label': "{{ lab_odf_node_label }}"}
      - {'name': "{{ lab_name }}-node-5", 'label': "{{ lab_odf_node_label }}"}
      - {'name': "{{ lab_name }}-node-6", 'label': "{{ lab_odf_node_label }}"}

- name: 'Setup Multicluster Engine (MCE)'
  gather_facts: false
  hosts: ['lab']
  roles:
    - role: 'ocp_mce'
      vars:
        ocp_mce_install: true
        ocp_mce_path: '/root/labs/cnv/config'
      tags:
        - 'postinst'
        - 'mce'
