---
dnsmasq_cache_size: 250
dnsmasq_conf_snippets:
  - {src: 'dnsmasq-capi.conf.j2', dest: 'capi.conf'}
  - {src: 'records.conf.j2', dest: 'assisted-installer.conf'}
dnsmasq_except_interfaces:
  - 'podman*'
  - 'vnet*'
dnsmasq_host_records:
  - {hostname: 'assisted-service-2.assisted-installer.com', ipaddr: '10.0.130.180'}
  - {hostname: 'assisted-image-2.assisted-installer.com', ipaddr: '10.0.130.180'}
dnsmasq_max_cache_ttl: 300
dnsmasq_no_negcache: true
dnsmasq_no_resolv: true
dnsmasq_servers:
  - {address: '10.0.0.2'}
  - {address: '1.1.1.1'}
