---
galaxy_info:
  role_name: ocp_hcp
  namespace: mlorenzofr
  author: 'Manuel Lorenzo'
  description: 'This role creates and deploys an hosted cluster (hypershift)'
  company: 'Red Hat'
  license: 'BSD'
  min_ansible_version: '2.12'
  platforms:
    - name: 'EL'
      versions:
        - '8'
  galaxy_tags: []
dependencies:
  - name: 'ocp_assisted_service'
    tags: ['assisted']
  - name: 'ocp_metallb'
    tags: ['metallb']
    vars:
      ocp_metallb_pool_ips: "{{ ocp_hcp_kubeapi_ips }}"
      ocp_metallb_pool_name: "{{ ocp_hcp_kubeapi_name }}"
