---
galaxy_info:
  role_name: ocp_quay
  namespace: mlorenzofr
  author: 'Manuel Lorenzo'
  description: 'Install and configure Quay Operator'
  company: 'Red Hat'
  license: 'BSD'
  min_ansible_version: '2.12'
  platforms:
    - name: 'EL'
      versions:
        - '8'
  galaxy_tags: []
dependencies:
  - name: 'ocp_odf'
