---
- name: 'Create local-storage installation manifest'
  ansible.builtin.template:
    src: 'localstorage-init.yaml.j2'
    dest: "{{ ocp_localstorage_path }}/localstorage-subscription.yaml"
    mode: '0644'
  notify: 'localstorage install'

- name: 'Create LocalVolumes manifests'
  ansible.builtin.template:
    src: 'localvolume.yaml.j2'
    dest: "{{ ocp_localstorage_path }}/localvolume-{{ item.name }}.yaml"
    mode: '0644'
  loop: "{{ ocp_localstorage_volumes }}"
  notify: 'localstorage install'

- name: 'Create LocalVolumeSets manifests'
  ansible.builtin.template:
    src: 'localvolumeset.yaml.j2'
    dest: "{{ ocp_localstorage_path }}/localvolumeset-{{ item.name }}.yaml"
    mode: '0644'
  loop: "{{ ocp_localstorage_volumesets }}"
  notify: 'localstorage install'
