---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fakefish-cnvn-spoke-2-default
  name: fakefish-cnvn-spoke-2-default
  namespace: fakefish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakefish-cnvn-spoke-2-default
  strategy: {}
  template:
    metadata:
      labels:
        app: fakefish-cnvn-spoke-2-default
    spec:
      volumes:
      - name: kubevirt-kubeconfig
        secret:
          secretName: kubevirt-cluster-kubeconfig
      containers:
      - image: quay.io/mlorenzofr/fakefish:latest
        imagePullPolicy: Always
        name: fakefish
        resources: {}
        args:
        - "--remote-bmc"
        - "cnvn-spoke-2_default"
        - "--tls-mode"
        - "disabled"
        volumeMounts:
        - name: kubevirt-kubeconfig
          readOnly: true
          mountPath: /var/tmp/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fakefish-cnvn-spoke-2-default
  name: fakefish-cnvn-spoke-2-default
  namespace: fakefish
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: fakefish-cnvn-spoke-2-default
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fakefish-cnvn-spoke-2-default
  namespace: fakefish
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: "Service"
    name: fakefish-cnvn-spoke-2-default
    weight: null
