---
- name: 'Create managedcluster manifest'
  ansible.builtin.template:
    src: 'managedcluster.yaml.j2'
    dest: "{{ acm_cwd }}/managedcluster-{{ cluster }}.yaml"
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: 'Create import namespace'
  kubernetes.core.k8s:
    name: "{{ cluster }}"
    api_version: v1
    kind: Namespace
    state: present
    # labels:
    #  cluster.open-cluster-management.io/managedCluster: '{{ cluster }}'

- name: 'Create kubeconfig secret'
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: 'v1'
      kind: 'Secret'
      metadata:
        name: 'auto-import-secret'
        namespace: "{{ cluster }}"
      type: 'Opaque'
      stringData:
        autoImportRetry: "5"
      data:
        kubeconfig: "{{ kubeconfig | b64encode }}"

- name: 'Apply managedcluster manifest'
  kubernetes.core.k8s:
    state: 'present'
    src: "{{ acm_cwd }}/managedcluster-{{ cluster }}.yaml"
  ignore_errors: "{{ ansible_check_mode }}"
...
