---
apiVersion: v1
metadata:
  name: dgonspk
baseDomain: local.lab
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: 192.168.125.0/24
  clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
compute:
  - name: worker
    architecture: amd64
    hyperthreading: Enabled
    replicas: 0
controlPlane:
  name: master
  architecture: amd64
  hyperthreading: Enabled
  replicas: 1
platform:
  none: {}
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
