---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-deployment
  namespace: workload
  labels:
    app: workload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
        - name: workload-container
          image: image-registry.openshift-image-registry.svc:5000/workload/nginx:latest
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: temp-volume
              mountPath: /var/cache/nginx
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 8080
        - name: stress-container
          image: image-registry.openshift-image-registry.svc:5000/workload/stress:latest
          command: ["stress"]
          args: ["--cpu", "2", "--timeout", "60s"]
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"
      volumes:
        - name: temp-volume
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: workload-service
  namespace: workload
spec:
  selector:
    app: workload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: workload
data:
  nginx.conf: |
    worker_processes  1;
    pid               /tmp/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        server {
            listen 8080;

            server_name localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
        }
    }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workload-hpa
  namespace: workload
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workload-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
