---
apiVersion: v1
metadata:
  name: elior
baseDomain: local.lab
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: 192.168.140.0/24
  clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
compute:
  - name: worker
    architecture: amd64
    hyperthreading: Enabled
    replicas: 0
controlPlane:
  name: master
  architecture: amd64
  hyperthreading: Enabled
  replicas: 3
platform:
  baremetal:
    apiVIPs: ['192.168.140.10']
    ingressVIPs: ['192.168.140.11']
    externalMACAddress: ee:11:00:00:aa:00
    provisioningNetwork: Disabled
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
