---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: 'spoke-multiarch'
  labels:
    cloud: 'auto-detect'
    vendor: 'auto-detect'
spec:
  hubAcceptsClient: true
