---
lab_host_packages:
  - 'bash-completion'
  - 'chrony'
  - 'cpio'
  - 'dnsmasq'
  - 'git'
  - 'haproxy'
  - 'jq'
  - 'kpartx'
  - 'libvirt'
  - 'libvirt-daemon-driver-qemu'
  - 'nmap'
  - 'nmstate'
  - 'policycoreutils-python-utils'
  # - 'python3-cherrypy'
  - 'qemu-kvm'
  - 'rsync'
  - 'squid'
  - 'tar'
  - 'telnet'
  - 'tmux'
  - 'vim-enhanced'
  # - 'virt-install'
...
