---
lab_host_packages:
  - 'bash-completion'
  - 'chrony'
  - 'cpio'
  - 'dnsmasq'
  - 'git'
  - 'jq'
  - 'kpartx'
  - 'libguestfs'
  - 'libguestfs-tools-c'
  - 'libvirt'
  - 'libvirt-daemon-driver-qemu'
  - 'nmap'
  - 'nmstate'
  - 'policycoreutils-python-utils'
  # - 'python3-cherrypy'
  - 'qemu-kvm'
  - 'rsync'
  - 'skopeo'
  - 'squid'
  - 'tar'
  - 'telnet'
  - 'tmux'
  - 'vim-enhanced'
  - 'virt-install'
lab_host_pip_packages:
  - 'strato-skipper==2.0.2'
lab_host_scripts:
  - 'extract-ignition.sh'
  - 'kubelet-renew-certificates.sh'
  - 'ocp-snapshot.sh'
...
