---
- name: 'Check MultiCluster Engine status'
  ansible.builtin.command:
    cmd: '/usr/local/bin/oc get multiclusterengine'
  register: __mce_status
  check_mode: false
  changed_when: false
  failed_when: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Install MultiCluster Engine Operator'
  ansible.builtin.command:
    cmd: "/usr/local/bin/oc apply -f {{ ocp_mce_path }}/mce-subscription.yaml"
  when: __mce_status.rc != 0

- name: 'Waiting until the operator is installed'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc -n {{ ocp_mce_ns }} wait
      --for=jsonpath='{.status.state}'=AtLatestKnown
      subscription/multicluster-engine --timeout=300s
  when: __mce_status.rc != 0

- name: 'Create MultiClusterEngine resource'
  ansible.builtin.command:
    cmd: "/usr/local/bin/oc apply -f {{ ocp_mce_path }}/mce.yaml"
  when: __mce_status.rc != 0

- name: 'Waiting until the MultiCluster engine is available'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc wait multiclusterengine/{{ ocp_mce_name }}
      --for=jsonpath='{.status.phase}'=Available
      --timeout=300s
  changed_when: false
...
