---
- name: 'Create MultiCluster Engine manifests'
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ ocp_mce_path }}/{{ item.dest }}"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
  loop:
    - {template: 'init.yaml.j2', dest: 'mce-subscription.yaml'}
    - {template: 'mce.yaml.j2', dest: 'mce.yaml'}
  notify: 'mce install'
