---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: quay
rendezvousIP: 192.168.129.65
hosts:
  - hostname: quay-node-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:65
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:65
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: quay-node-2
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:66
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:66
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: quay-node-3
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:67
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:67
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
