---
- name: 'Set disableAllDefaultSources'
  kubernetes.core.k8s:
    definition:
      apiVersion: 'config.openshift.io/v1'
      kind: 'OperatorHub'
      metadata:
        name: 'cluster'
      spec:
        disableAllDefaultSources: "{{ ocp_olm_disablealldefaultsources }}"
