---
- name: 'Create subscription manifest'
  ansible.builtin.template:
    src: 'v0.yaml.j2'
    dest: "{{ ocp_olm_path }}/{{ item.name }}-subscription.yaml"
    mode: '0644'

- name: 'Install subscription manifest'
  kubernetes.core.k8s:
    state: 'present'
    src: "{{ ocp_olm_path }}/{{ item.name }}-subscription.yaml"

- name: 'Waiting until the operator is installed'
  ansible.builtin.command:
    cmd: >
      {{ ocp_olm_kubectl }} -n {{ item.ns }} wait
      --for=jsonpath='{.status.state}'=AtLatestKnown
      subscription/{{ item.name }} --timeout=300s
  changed_when: false
  failed_when: false
