---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: nutanix-csi-crs
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      ccm: nutanix
  resources:
    - kind: ConfigMap
      name: nutanix-csi
    - kind: Secret
      name: nutanix-csi-secret
  strategy: ApplyOnce
---
apiVersion: v1
kind: Secret
metadata:
  name: nutanix-csi-secret
  namespace: default
stringData:
  nutanix-csi-secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
        name: ntnx-pc-secret
        namespace: openshift-cluster-csi-drivers
    stringData:
        # key: <PRISM-ELEMENT>:<PRISM-ELEMENT-PORT>:<USERNAME>:<PASSWORD>
        key: <redacted>:9440:<redacted>:<redacted>
    ---
    apiVersion: v1
    kind: Secret
    metadata:
        name: ntnx-secret
        namespace: openshift-cluster-csi-drivers
    data:
        # key: <PRISM-CENTRAL>:<PRISM-CENTRAL-PORT>:<USERNAME>:<PASSWORD> base64 encoded
        key: <redacted>
type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nutanix-csi
  namespace: default
data:
  nutanix-csi.yaml: |
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
        name: openshift-cluster-csi-drivers
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
        name: nutanix-csi-operator-beta
        namespace: openshift-marketplace
    spec:
        displayName: Nutanix Beta
        publisher: Nutanix-dev
        sourceType: grpc
        image: quay.io/ntnx-csi/nutanix-csi-operator-catalog:latest
        updateStrategy:
            registryPoll:
                interval: 5m
