---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: mcgh
rendezvousIP: 192.168.125.72
hosts:
  - hostname: mcgh-node-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:72
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:72
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: mcgh-node-2
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:73
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:73
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: mcgh-node-3
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:74
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:74
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
