---
apiVersion: v1
kind: Namespace
metadata:
  name: multicluster-global-hub
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: multicluster-global-hub-operatorgroup
  namespace: multicluster-global-hub
spec:
  targetNamespaces:
    - multicluster-global-hub
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-global-hub-operator-rh
  namespace: multicluster-global-hub
spec:
  channel: "release-1.2"
  installPlanApproval: Automatic
  name: multicluster-global-hub-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
