---
- name: 'Prepare worker nodes'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_network_name: 'lab-network'
    lab_node_network_base: '192.168.125.'
    lab_node_disk_pool: 'ocp'
    lab_name: ''
    lab_mac_base: 'be:be:ca:fe:05:'
    ocp_baremetal_infras: []

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - ocp_baremetal
