---
# Run it with: ansible-playbook server.yaml
#
# This playbook configures the OS to host Openshift labs.

- name: 'Configure labs server'
  hosts:
    - 'lab'

  roles:
    - role: dnsmasq
      tags: ['dnsmasq']
    - 'lab_host'
    - role: 'haproxy'
      tags: ['haproxy']
    - role: 'kind'
      tags: ['kind']
