---
apiVersion: v1
metadata:
  name: okdb
baseDomain: local.lab
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: 192.168.125.0/24
  clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
compute:
  - name: worker
    architecture: amd64
    hyperthreading: Enabled
    replicas: 0
controlPlane:
  name: master
  architecture: amd64
  hyperthreading: Enabled
  replicas: 3
platform:
  baremetal:
    apiVIPs: ['192.168.125.85']
    ingressVIPs: ['192.168.125.86']
    externalMACAddress: be:be:ca:fe:08:ff
    provisioningNetwork: Disabled
    externalBridge: "lab-network"
    hosts:
      - name: okdb-master-1
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/okdb-master-1
          username: <redacted>
          password: <redacted>
          disableCertificateVerification: True
        bootMACAddress: be:be:ca:fe:08:81
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: okdb-master-2
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/okdb-master-2
          username: <redacted>
          password: <redacted>
          disableCertificateVerification: True
        bootMACAddress: be:be:ca:fe:08:82
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: okdb-master-3
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/okdb-master-3
          username: <redacted>
          password: <redacted>
          disableCertificateVerification: True
        bootMACAddress: be:be:ca:fe:08:83
        rootDeviceHints:
          deviceName: "/dev/vda"
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
