---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: multiarch
rendezvousIP: 192.168.125.61
hosts:
  - hostname: multiarch-master-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:61
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:61
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: multiarch-master-2
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:62
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:62
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: multiarch-master-3
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:63
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:63
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
