apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-manager
  namespace: default
rules:
- apiGroups: ["kubevirt.io"]
  resources:
  - virtualmachines
  - virtualmachineinstances
  - virtualmachineinstancereplicasets
  - datavolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: ["subresources.kubevirt.io"]
  resources:
  - virtualmachines/start
  - virtualmachines/stop
  - virtualmachines/restart
  - virtualmachineinstances/addvolume
  - virtualmachineinstances/removevolume
  verbs:
  - update
- apiGroups: ["upload.cdi.kubevirt.io"]
  resources:
  - uploadtokenrequests
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: ["cdi.kubevirt.io"]
  resources:
  - datavolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources:
  - events
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-manager-fakefish
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: fakefish
roleRef:
  kind: Role
  name: vm-manager
  apiGroup: rbac.authorization.k8s.io
