---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: acm1
rendezvousIP: 192.168.125.75
hosts:
  - hostname: acm1-node-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:75
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:75
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
