---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: cnvn
rendezvousIP: 192.168.125.41
hosts:
  - hostname: cnvn-master-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:41
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:41
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: cnvn-master-2
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:42
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:42
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: cnvn-master-3
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:43
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:43
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
