---
# This playbook installs a complete lab with ODF
#
# Run it with:
#   ap labs/odf/odf.yaml

- name: 'Import compact playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/compact.yml
  vars:
    lab_name: 'odf'
    lab_node_memory: 32000
    lab_node_disk_data: 150
    start_install: true

- name: 'Import odf setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/odf.yaml
  vars:
    lab_name: 'odf'
