---
- name: 'Install a new lab using the Appliance Bundle tool'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_appliance: True
    lab_mac_base: 'be:be:ca:fe:03:'
    lab_node_disk_sys: 150
    lab_node_disk_data: 1
    lab_node_network_base: '192.168.125.'
    lab_node_role: 'node'
    lab_path: '/home/ocp-labs'
    lab_pull_secret_install: '{"auths":{"":{"auth":"dXNlcjpwYXNz"}}}'
    libvirt_image_dir: '/home/libvirt-ocp'

    lab_name: 'appliance'
    lab_hosts: []
    lab_abi_ip: ""
    lab_api_ips: []
    lab_ingress_ips: []

  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'

  roles:
    - 'lab'

  tasks:
    - name: 'Execute base handlers'
      ansible.builtin.meta: flush_handlers

    - name: 'Remove CD-ROM on VMs'
      ansible.builtin.command:
        cmd: >
          virsh detach-disk
          {{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}
          hdc --config
      loop: "{{ lab_hosts }}"
      loop_control:
        extended: true

    - name: 'Copy configuration files to deploy directory'
      ansible.builtin.copy:
        src: "{{ lab_path }}/{{ lab_name }}/config/appliance-config.yaml"
        dest: "{{ lab_path }}/{{ lab_name }}/deploy/appliance-config.yaml"
        remote_src: true
      ignore_errors: "{{ ansible_check_mode }}"
      notify:
        - 'bundle build'

    - name: 'Copy configuration files to deploy directory'
      ansible.builtin.copy:
        src: "{{ lab_path }}/{{ lab_name }}/config/{{ item }}"
        dest: "{{ lab_path }}/{{ lab_name }}/deploy/{{ item }}"
        remote_src: true
      ignore_errors: "{{ ansible_check_mode }}"
      loop:
        - 'install-config.yaml'
        - 'agent-config.yaml'
      notify:
        - 'agent build'

  handlers:
    - name: 'Clean appliance builds'
      ansible.builtin.command:
        cmd: >
          podman run --rm
            --pull newer
            --privileged
            --net=host
            -v {{ lab_path }}/{{ lab_name }}/deploy/:/assets:Z
            {{ lab_appliance_image }}
            clean
      listen:
        - 'bundle build'

    - name: 'Generate appliance bundle'
      ansible.builtin.command:
        cmd: >
          podman run --rm
            --pull newer
            --privileged
            --net=host
            -v {{ lab_path }}/{{ lab_name }}/deploy/:/assets:Z
            {{ lab_appliance_image }}
            build
      listen:
        - 'bundle build'

    # This task is too slow, it must be reviewed
    # - name: 'Copy appliance disk to libvirt storage directory'
    #   ansible.posix.synchronize:
    #     src: "{{ lab_path }}/{{ lab_name }}/deploy/appliance.raw"
    #     dest: "{{ libvirt_image_dir }}/{{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}.raw"
    #   delegate_to: "{{ inventory_hostname }}"
    #   loop: "{{ lab_hosts }}"
    #   loop_control:
    #     extended: true
    #   listen:
    #     - 'bundle build'

    - name: 'Copy appliance disk to libvirt storage directory'
      ansible.builtin.command:
        cmd: >
          cp -f {{ lab_path }}/{{ lab_name }}/deploy/appliance.raw
          {{ libvirt_image_dir }}/{{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}.raw
      loop: "{{ lab_hosts }}"
      loop_control:
        extended: true
      listen:
        - 'bundle build'

    - name: 'Remove old agent-config files'
      ansible.builtin.file:
        path: "{{ item }}"
        state: 'absent'
      loop:
        - "{{ lab_path }}/{{ lab_name }}/deploy/agentconfig.noarch.iso"
        - "{{ lab_path }}/{{ lab_name }}/deploy/auth"
      listen:
        - 'agent build'

    - name: 'Get Openshift cache version'
      ansible.builtin.shell:
        cmd: >
          grep -Eo 'cache/[^/]+' temp/scripts/guestfish/guestfish.sh | uniq
        chdir: "{{ lab_path }}/{{ lab_name }}/deploy"
      register: __appliance_ocp_version
      listen:
        - 'agent build'

    - name: 'Generate bootstrap ISO image'
      ansible.builtin.command:
        cmd: >
          {{ lab_path }}/{{ lab_name }}/deploy/{{ __appliance_ocp_version.stdout }}/openshift-install
            agent create config-image
            --dir {{ lab_path }}/{{ lab_name }}/deploy
      listen:
        - 'agent build'

    - name: 'Copy ISO image to libvirt image directory'
      ansible.builtin.copy:
        src: "{{ lab_path }}/{{ lab_name }}/deploy/agentconfig.noarch.iso"
        dest: "{{ libvirt_image_dir }}/{{ lab_name }}-agentconfig.iso"
        remote_src: true
      listen:
        - 'agent build'

    - name: 'Attach appliance disk'
      ansible.builtin.command:
        cmd: >
          virsh attach-disk
          {{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}
          {{ libvirt_image_dir }}/{{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}.raw
          sda --persistent
      loop: "{{ lab_hosts }}"
      loop_control:
        extended: true
      listen:
        - 'bundle build'

    - name: 'Attach agent-config disk'
      ansible.builtin.command:
        cmd: >
          virsh attach-disk
          {{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}
          {{ libvirt_image_dir }}/{{ lab_name }}-agentconfig.iso
          sdb --persistent --mode readonly --targetbus usb
      loop: "{{ lab_hosts }}"
      loop_control:
        extended: true
      listen:
        - 'agent build'

    - name: 'Start VMs'
      ansible.builtin.command:
        cmd: >
          virsh start
          {{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}
      loop: "{{ lab_hosts }}"
      loop_control:
        extended: true
      listen:
        - 'bundle build'
        - 'agent build'
      when: start_install | default(False)
