---
# To start the installation in background inside a tmux session use `-e "start_install=true"`
#
# Run examples:
#   - ansible-playbook playbooks/base/compact.yml -e "start_install=true"
#   - ansible-playbook playbooks/base/compact.yml -e "lab_node_memory=32000" -e "lab_node_disk_data=60"
#   - ansible-playbook playbooks/base/compact.yml -e "lab_node_memory=32000" -e "lab_node_disk_data=150"
- name: 'Install Openshift compact cluster'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_api_ips: ["{{ lab_node_network_base }}10"]
    lab_bootstrap_ip: "{{ lab_node_network_base }}100"
    lab_bootstrap_mac: "{{ lab_mac_base }}00"
    lab_ingress_ips: ["{{ lab_node_network_base }}11"]
    lab_name: 'standard'
    lab_master_replicas: 3
    lab_mac_base: 'be:be:ca:fe:02:'
    lab_platform: 'baremetal'
    lab_redfish_ip: "{{ lab_node_network_base }}1"
    lab_node_disk_data: 1
    lab_node_network_base: '192.168.125.'
    libvirt_image_dir: '/home/libvirt-ocp'
    lab_hosts:
      - {'id': '21'}
      - {'id': '22'}
      - {'id': '23'}

  roles:
    - 'lab'

  tasks:
    - name: 'Execute base handlers'
      ansible.builtin.meta: flush_handlers

    - name: 'Copy configuration files to deploy directory'
      ansible.builtin.copy:
        src: "{{ lab_path }}/{{ lab_name }}/config/{{ item }}"
        dest: "{{ lab_path }}/{{ lab_name }}/deploy/{{ item }}"
        mode: '0640'
        remote_src: true
      loop:
        - 'install-config.yaml'

    - name: 'Generate cluster manifests'
      ansible.builtin.command:
        cmd: "/usr/local/bin/openshift-baremetal-install create cluster-manifests --dir {{ lab_path }}/{{ lab_name }}/deploy"
        creates: "{{ lab_path }}/{{ lab_name }}/deploy/.openshift_install_state.json"

    - name: 'Launch install process in a tmux session'
      ansible.builtin.command:
        cmd: >
          /usr/bin/tmux new-session -s ocp-install-{{ lab_name }} -d
          "/usr/local/bin/openshift-baremetal-install --dir {{ lab_path }}/{{ lab_name }}/deploy --log-level debug create cluster"
      register: tmux_status
      when: start_install | default(False)

    - name: 'Wait for kubeconfig file'
      ansible.builtin.wait_for:
        path: "{{ lab_path }}/{{ lab_name }}/deploy/auth/kubeconfig"
        state: 'present'
      when: start_install | default(False)

    - name: 'Waiting until the installation finishes'
      ansible.builtin.command:
        cmd: >
          oc get clusterversion -o jsonpath='{.items[*].status.conditions[?(@.type=="Available")].status}'
      register: install_status
      environment:
        KUBECONFIG: "{{ lab_path }}/{{ lab_name }}/deploy/auth/kubeconfig"
        PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
      retries: 125
      delay: 30
      until: install_status.stdout == 'True'
      changed_when: False
      when: start_install | default(False)
