---
- name: 'Setup Single Node Openshift (SNO) with Agent Based Installation (ABI)'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_abi: True
    lab_abi_ip: "{{ lab_node_network }}.31"
    lab_api_ips: ["{{ lab_node_network }}.31"]
    lab_ingress_ips: ["{{ lab_node_network }}.31"]
    lab_name: 'sno'
    lab_master_replicas: 1
    lab_mac_base: 'be:be:ca:fe:03:'
    lab_node_disk_data: 1
    lab_node_network: '192.168.125'
    lab_hosts:
      - {'id': '31', 'iface':'enp1s0'}
    libvirt_image_dir: '/home/libvirt-ocp'

  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'

  roles:
    - 'lab'

  tasks:
    - name: 'Copy configuration files to deploy directory'
      ansible.builtin.copy:
        src: "{{ lab_path }}/{{ lab_name }}/config/{{ item }}"
        dest: "{{ lab_path }}/{{ lab_name }}/deploy/{{ item }}"
        remote_src: true
      loop:
        - 'install-config.yaml'
        - 'agent-config.yaml'

    - name: 'Generate cluster manifests'
      ansible.builtin.command:
        cmd: "/usr/local/bin/openshift-install agent create cluster-manifests --dir {{ lab_path }}/{{ lab_name }}/deploy"
        creates: "{{ lab_path }}/{{ lab_name }}/deploy/.openshift_install_state.json"

    - name: 'Generate bootstrap ISO image'
      ansible.builtin.command:
        cmd: "/usr/local/bin/openshift-install agent create image --dir {{ lab_path }}/{{ lab_name }}/deploy"
        creates: "{{ lab_path }}/{{ lab_name }}/deploy/agent.x86_64.iso"

    - name: 'Copy ISO image to libvirt image directory'
      ansible.builtin.copy:
        src: "{{ lab_path }}/{{ lab_name }}/deploy/agent.x86_64.iso"
        dest: "{{ libvirt_image_dir }}/{{ lab_name }}-agent-installer.iso"
        remote_src: true

# TODO
# attach the ISO to the VM and start it
