---
- name: 'Set watchAllNamespaces for provisioning'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc patch provisionings/provisioning-configuration
      -p '{"spec":{"watchAllNamespaces":true}}' --type merge
  listen:
    - 'set watch-all'

- name: 'Restart dnsmasq-virt service'
  ansible.builtin.service:
    name: 'dnsmasq-virt'
    state: 'restarted'
  listen: 'svc restart dnsmasq-virt'

- name: 'Create infrastructures'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc apply -f {{ ocp_baremetal_path }}/infra
  register: __baremetal_infra
  until: __baremetal_infra.rc == 0
  retries: 5
  delay: 30
  when: ocp_baremetal_install
  listen:
    - 'update infrastructure'

# TODO
# wait action for bmh / agent
