---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-provider-role
  namespace: hardware-inventory
rules:
- apiGroups:
    - agent-install.openshift.io
  resources:
    - agents
  verbs:
    - '*'
---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: hosted
  namespace: hardware-inventory
spec:
  additionalNTPSources:
    - 192.168.125.1
  pullSecretRef:
    name: pull-secret-hosted
  sshAuthorizedKey: <redacted>
