---
- name: 'Import compact playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/compact.yml
  tags:
    - 'ocp'
  vars:
    lab_name: 'okd'
    lab_node_memory: 28000
    lab_node_disk_data: 60
    start_install: true

- name: 'Import HCP setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/hive.yml
  tags:
    - 'postinst'
  vars:
    lab_name: 'okd'
    lab_mac_base: 'be:be:ca:fe:02:'

    ocp_assisted_service_images:
      - ocp_version: '4.15.0'
        arch: 'x86_64'
        version: '415.92.202402130021-0'

    ocp_baremetal_infras:
      - name: 'sno'
        ns: 'hive-sno'
        ntp: ['192.168.125.1']
        pullsecret: "{{ lab_pull_secret }}"
        sshkey: "{{ lab_ssh_pubkey }}"
        redfish: '192.168.125.1'
        inventory:
          - {'name': "{{ lab_name }}-bmh-1", 'id': '25'}

    ocp_hive_clusterimagesets:
      - name: 'okd-4.15.0-x86-64-20240118223523'
        image: 'registry.ci.openshift.org/origin/release-scos:4.15.0-0.okd-scos-2024-01-18-223523'
        visible: 'true'

    ocp_hive_clusters:
      - name: 'sno'
        ns: 'hive-sno'
        image: 'okd-4.15.0-x86-64-20240118223523'
        service_network: '172.32.0.0/16'
        host_network: '192.168.125.0/24'
        masters: 1
        pullsecret: "{{ lab_pull_secret_b64 }}"
        sshkey: "{{ lab_ssh_pubkey }}"
        domain: 'local.lab'
        ip: '192.168.125.25'

- name: 'Prepare okd cluster configuration'
  ansible.builtin.import_playbook: ../../playbooks/jobs/hive-config.yml
  vars:
    lab_name: 'okd'
    lab_path: '/root/labs'
    hive_cluster_name: 'sno'
    hive_ns: 'hive-sno'
  tags:
    - 'postinst'
    - 'okd'
    - 'okd-config'
