---
- name: 'Install MetalLB and create an ingress for a HostedCluster'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_name: ''
    lab_path: '/root/labs'
    lab_install: true
    ocp_metallb_path: "{{ lab_path }}/{{ lab_name }}/{{ spoke_name }}"
    ocp_metallb_pool_name: "{{ spoke_name }}-lb-pool"
    ocp_metallb_pool_ips: "{{ spoke_lb_ips }}"
    spoke_name: ''
    spoke_lb_ips: []

  environment:
    KUBECONFIG: "{{ lab_path }}/{{ lab_name }}/{{ spoke_name }}/auth/kubeconfig"

  roles:
    - ocp_metallb

  pre_tasks:
    - name: 'Test lab_name'
      ansible.builtin.fail:
        msg: 'Variable lab_name is empty'
      when: lab_name | length == 0

    - name: 'Test spoke_name'
      ansible.builtin.fail:
        msg: 'Variable spoke_name is empty'
      when: spoke_name | length == 0

    - name: 'Test spoke_lb_ips type'
      ansible.builtin.fail:
        msg: 'Variable spoke_lb_ips is not a list'
      when: spoke_lb_ips | type_debug != "list"

    - name: 'Test spoke_lb_ips'
      ansible.builtin.fail:
        msg: 'Variable spoke_lb_ips is empty'
      when: spoke_lb_ips | length == 0

    - name: 'Wait for OLM ClusterOperator'
      kubernetes.core.k8s_info:
        api_version: 'config.openshift.io/v1'
        kind: 'ClusterOperator'
        name: 'operator-lifecycle-manager-catalog'
      register: __hcp_olm
      until:
        - __hcp_olm.resources | length > 0
        - __hcp_olm.resources[0].status.conditions is defined
        - __hcp_olm.resources[0].status.conditions | selectattr('type', 'equalto', 'Available') | selectattr('status', 'equalto', 'True') | length > 0
      retries: 60
      delay: 30

  tasks:
    - name: 'Create metallb ingress'
      kubernetes.core.k8s:
        definition:
          kind: 'Service'
          apiVersion: 'v1'
          metadata:
            annotations:
              metallb.universe.tf/address-pool: "{{ ocp_metallb_pool_name }}"
            name: 'metallb-ingress'
            namespace: 'openshift-ingress'
          spec:
            ports:
              - name: 'http'
                protocol: 'TCP'
                port: 80
                targetPort: 80
              - name: 'https'
                protocol: 'TCP'
                port: 443
                targetPort: 443
            selector:
              ingresscontroller.operator.openshift.io/deployment-ingresscontroller: 'default'
            type: LoadBalancer
      when: lab_install
