---
- name: 'Extract HostedCluster auth configuration'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_path: '/root/labs'

  vars_prompt:
    - name: lab_name
      prompt: 'lab name'
      private: false
    - name: hcp_name
      prompt: 'hosted cluster name'
      private: false

  tasks:
    - name: 'Test lab_name'
      ansible.builtin.fail:
        msg: 'Variable lab_name is empty'
      when: lab_name | length == 0

    - name: 'Create hosted cluster deploy directory'
      ansible.builtin.file:
        path: "{{ lab_path }}/{{ lab_name }}/{{ hcp_name }}/auth"
        mode: '0750'
        state: 'directory'

    - name: 'Extract hosted cluster kubeconfig'
      ansible.builtin.command:
        cmd: >
          /usr/local/bin/oc extract -n {{ hcp_name }}-{{ hcp_name }}
          secret/admin-kubeconfig
          --to={{ lab_path }}/{{ lab_name }}/{{ hcp_name }}/auth
          --confirm
        creates: "{{ lab_path }}/{{ lab_name }}/{{ hcp_name }}/auth/kubeconfig"
      environment:
        KUBECONFIG: "{{ lab_path }}/{{ lab_name }}/deploy/auth/kubeconfig"

    - name: 'Extract hosted cluster kubeadmin console password'
      ansible.builtin.command:
        cmd: >
          /usr/local/bin/oc extract -n {{ hcp_name }}-{{ hcp_name }}
          secret/kubeadmin-password
          --to={{ lab_path }}/{{ lab_name }}/{{ hcp_name }}/auth
          --confirm
        creates: "{{ lab_path }}/{{ lab_name }}/{{ hcp_name }}/auth/password"
      environment:
        KUBECONFIG: "{{ lab_path }}/{{ lab_name }}/deploy/auth/kubeconfig"
