---
galaxy_info:
  role_name: ocp_cnv
  namespace: mlorenzofr
  author: 'Manuel Lorenzo'
  description: 'Install and configure Openshift Virtualization (CNV) Operator'
  company: 'Red Hat'
  license: 'BSD'
  min_ansible_version: '2.12'
  platforms:
    - name: 'EL'
      versions:
        - '8'
        - '9'
  galaxy_tags: []
dependencies: []
