---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: calico
rendezvousIP: 192.168.125.61
hosts:
  - hostname: calico-node-1
    interfaces:
      - name: eth0
        macAddress: ca:11:c0:00:00:61
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: ca:11:c0:00:00:61
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: calico-node-2
    interfaces:
      - name: eth0
        macAddress: ca:11:c0:00:00:62
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: ca:11:c0:00:00:62
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: calico-node-3
    interfaces:
      - name: eth0
        macAddress: ca:11:c0:00:00:63
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: ca:11:c0:00:00:63
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
