---
apiVersion: v1
metadata:
  name: calico
baseDomain: local.lab
networking:
  networkType: Calico
  machineNetwork:
    - cidr: 192.168.125.0/24
  clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
compute:
  - name: worker
    architecture: amd64
    hyperthreading: Enabled
    replicas: 0
controlPlane:
  name: master
  architecture: amd64
  hyperthreading: Enabled
  replicas: 3
platform:
  baremetal:
    apiVIPs: ['192.168.125.200']
    ingressVIPs: ['192.168.125.201']
    externalMACAddress: ca:11:c0:00:00:00
    provisioningNetwork: Disabled
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
    - baremetal
    - MachineAPI
    - marketplace
    - OperatorLifecycleManager
    - Console
    - Ingress
    - Storage
    - NodeTuning
    - DeploymentConfig
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
