---
galaxy_info:
  role_name: ocp_baremetal
  namespace: mlorenzofr
  author: 'Manuel Lorenzo'
  description: 'Creates and applies the manifests required for Baremetal infrastructure on Openshift Cluster'
  company: 'Red Hat'
  license: 'BSD'
  min_ansible_version: '2.12'
  platforms:
    - name: 'EL'
      versions:
        - '8'
  galaxy_tags: []
dependencies: []
