---
- name: 'Include custom os variables'
  ansible.builtin.include_vars:
    file: vars/os.yaml

- name: 'Install required packages'
  ansible.builtin.package:
    name: "{{ packages }}"
    state: 'present'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Install k8s tools'
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.name }}"
    owner: 'root'
    group: 'root'
    mode: '0755'
    force: "{{ item.force }}"
  loop: "{{ k8s_tools }}"
  tags:
    - 'tools'

- name: 'Install kustomize'
  ansible.builtin.unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v{{ kustomize_version }}/kustomize_v{{ kustomize_version }}_linux_amd64.tar.gz"
    remote_src: true
    dest: '/usr/local/bin/'
    owner: 'root'
    group: 'root'
    mode: '0755'
  tags:
    - 'tools'

- name: 'Install helm'
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    include: ['linux-amd64/helm']
    remote_src: true
    dest: '/usr/local/bin/'
    owner: 'root'
    group: 'root'
    mode: '0755'
    extra_opts:
      - '--strip-components=1'
  tags:
    - 'tools'

- name: 'Show internal IP'
  ansible.builtin.debug:
    msg: "{{ ansible_default_ipv4.address }}"

- name: 'Change default dns_servers for containers'
  ansible.builtin.lineinfile:
    path: '/usr/share/containers/containers.conf'
    regexp: '^#*dns_servers =.*'
    line: "dns_servers = {{ dns_servers }}"
  ignore_errors: "{{ ansible_check_mode }}"
