---
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: pinnedis-registry.pinnedis.local.lab/metadata
    skipTLS: true
mirror:
  platform:
    channels:
      - name: stable-4.16
        type: ocp
        minversion: '4.16.3'
        maxversion: '4.16.3'
      - name: stable-4.17
        type: ocp
        minversion: '4.17.0-0.nightly-2024-08-07-043456'
        maxversion: '4.17.0-0.nightly-2024-08-07-043456'
    graph: true
  operators: []
  additionalImages:
    - name: registry.access.redhat.com/ubi8/ubi:latest
  helm: {}
