kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: pinnedis-registry.pinnedis.local.lab/metadata
    skipTLS: true
mirror:
  platform:
    channels:
      - name: stable-4.16
        type: ocp
      - name: stable-4.17
        type: ocp
    graph: true
  operators: []
  additionalImages:
    - name: registry.access.redhat.com/ubi8/ubi:latest
  helm: {}
