---
# Installs ACM on an existing Openshift cluster
- name: 'Install Advanced Cluster Management (ACM)'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_dnsmasq_root: '/opt/dnsmasq'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_install: true
    lab_mac_base: 'be:be:ca:fe:02:'
    lab_name: 'standard'
    lab_network_name: 'lab-network'
    lab_node_network: '192.168.125'

    ocp_assisted_service_op: 'acm'

    ocp_baremetal_infras:
      - name: 'infra1'
        ns: 'hardware-inventory'
        pullsecret: "{{ lab_pull_secret }}"
        sshkey: "{{ lab_ssh_pubkey }}"
        ntp: ["{{ lab_node_network }}.1"]
        redfish: "{{ lab_node_network }}.1"
        inventory:
          - {'name': "{{ lab_name }}-worker-1", 'id': '51'}
          - {'name': "{{ lab_name }}-worker-2", 'id': '52'}

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_baremetal'
