---
# Installs ACM on an existing Openshift cluster
- name: 'Install Advanced Cluster Management (ACM)'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_install: true
    lab_mac_base: 'be:be:ca:fe:02:'
    lab_name: 'standard'
    lab_network_name: 'lab-network'
    lab_node_network: '192.168.125'

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_acm'
