---
# Installs ACM on an existing Openshift cluster
- name: 'Install Advanced Cluster Management (ACM)'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_name: 'standard'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_install: true

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_acm'
