---
# Install and configure Openshift Virtualization (CNV)
# In this scenario we expect an Openshift cluster installed

- name: 'Install and configure Openshift Virtualization (CNV)'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_name: 'standard'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_install: true

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_cnv'
