---
# Installs a hosted cluster
# This playbook expects a ctlplane lab.
- name: 'Install hosted control plane (HCP / Hypershift) with calico'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_dnsmasq_root: '/opt/dnsmasq'
    lab_name: 'ocp-lab-1'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_network_name: 'lab-network'
    lab_install: true
    ocp_metallb_pool_ips: '192.168.125.40-192.168.125.45'
    ocp_metallb_pool_name: "{{ lab_network_name }}"
    ocp_baremetal_infras:
      - name: 'hosted'
        ns: 'hardware-inventory'
        hypershift: true
        pullsecret: "{{ lab_pull_secret }}"
        sshkey: "{{ lab_ssh_pubkey }}"
        ntp: ['192.168.125.1']
        redfish: '192.168.125.1'
        inventory:
          - {'mac': 'be:be:ca:fe:02:05', 'ip': '192.168.125.25'}
          - {'mac': 'be:be:ca:fe:02:06', 'ip': '192.168.125.26'}
          - {'mac': 'be:be:ca:fe:02:07', 'ip': '192.168.125.27'}
    ocp_hcp_clusters:
      - name: 'hcp1'
        ns: 'hcp1'
        infra: 'hosted'
        agent_ns: 'hardware-inventory'
        pullsecret: "{{ lab_pull_secret_b64 }}"
        sshkey: "{{ lab_ssh_pubkey }}"
        version: '4.14.8'
        # network_type: 'Calico'
        service_network: '172.32.0.0/16'
        domain: 'local.lab'
        lb: '192.168.125.50'
        replicas: 3

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_hcp'

  pre_tasks:
    - name: 'Load personal vars'
      ansible.builtin.include_vars: 'user.yml'

  tasks:
    - name: 'Create calico directory'
      ansible.builtin.file:
        path: "{{ lab_configs }}/calico"
        state: 'directory'

    - name: 'Download Calico'
      ansible.builtin.unarchive:
        src: 'https://github.com/projectcalico/calico/releases/download/v3.27.0/ocp.tgz'
        dest: "{{ lab_configs }}/calico"
        remote_src: true
      ignore_errors: "{{ ansible_check_mode }}"
