---
# Install Hypershift on Openshift Cluster
- name: 'Install hosted control plane (HCP / Hypershift)'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_network_name: 'lab-network'
    lab_install: true
    lab_mac_base: 'be:be:ca:fe:02:'
    lab_node_network_base: '192.168.125.'
    lab_node_disk_pool: 'ocp'

    ocp_assisted_service_infraenvs: []
    ocp_hcp_clusters: []

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_hcp'
