---
# Install a SNO spoke cluster using hive
- name: 'Deploy a SNO spoke cluster using hive'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_dnsmasq_root: '/opt/dnsmasq'
    lab_name: 'standard'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_network_name: 'lab-network'
    lab_install: true
    lab_mac_base: 'be:be:ca:fe:02:'
    lab_node_network_base: '192.168.125.'

    ocp_baremetal_infras: []
    ocp_hive_clusters: []

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_hive'
