---
# Installs MCE and configures assisted-service on a existing cluster
# In this scenario we expect that control plane is installed and master have an
#   additional disk (40 GB) for assisted-service (LVMS)
- name: 'Install MultiCluster Engine (MCE)'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_dnsmasq_root: '/opt/dnsmasq'
    lab_name: 'standard'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_network_name: 'lab-network'
    lab_install: true
    lab_mac_base: 'be:be:ca:fe:02:'
    ocp_baremetal_infras:
      - name: 'hosted'
        ns: 'hardware-inventory'
        hypershift: true
        ntp: ['192.168.125.1']
        pullsecret: "{{ lab_pull_secret }}"
        sshkey: "{{ lab_ssh_pubkey }}"
        redfish: '192.168.125.1'
        inventory:
          - {'name': "{{ lab_name }}-bmh-1", 'id': '25'}
          - {'name': "{{ lab_name }}-bmh-2", 'id': '26'}
          - {'name': "{{ lab_name }}-bmh-3", 'id': '27'}

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_baremetal'
