---
# Install MultiCluster Global Hub on an existing Openshift cluster
- name: 'Install MultiCluster Global Hub'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_name: 'standard'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_network_name: 'lab-network'
    lab_install: true

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_mcgh'
