---
# Install and configure Openshift Data Foundation (ODF)
# In this scenario we expect an Openshift cluster installed with additional
#   disks for ODF.
# VMs requirements:
#  - 32 GB memory
#  - Additional disk with 150 GB
- name: 'Install and configure Openshift Data Foundation (ODF)'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_name: 'standard'
    lab_configs: "/root/labs/{{ lab_name }}/config"
    lab_install: true
    lab_odf_storageclass: 'lvms-vg1'

    ocp_odf_clusters:
      - name: 'ocs1'
        devicesets:
          - name: 'deviceset1'
            count: 1
            storage: '180Gi'
            storageclass: "{{ lab_odf_storageclass }}"
            replica: 3

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"

  roles:
    - 'ocp_odf'
