---
- name: 'upgrade-iso tasks'
  hosts: ['lab']

  environment:
    KUBECONFIG: "{{ lab_path }}/{{ lab_name }}/deploy/auth/kubeconfig"

  tasks:
    - name: 'Create appliance configuration for upgrade-iso'
      ansible.builtin.include_role:
        name: 'ocp_appliance'
        tasks_from: 'config.yaml'
      vars:
        ocp_appliance_cfg_dir: "{{ appliance_upgrade_dir }}"
        ocp_appliance_cfg_upgrade: true
        ocp_appliance_cmd_upgrade_iso: true
        ocp_appliance_image: 'quay.io/mlorenzofr/openshift-appliance'
        ocp_appliance_version: '4.18'
        include_tag: 'upgrade-iso'
        include_notify: 'openshift-appliance run'

    - name: 'Force execution of openshift-appliance commands'
      ansible.builtin.meta: flush_handlers

    - name: 'Search upgrade iso'
      ansible.builtin.find:
        path: "{{ appliance_upgrade_dir }}/"
        patterns: ".*\\.iso$"
        use_regex: true
      register: __upgrade_iso_file

    - name: 'Prepare VMs'
      ansible.builtin.import_tasks:
        file: 'virsh.yaml'
      when: __upgrade_iso_file.files[0].mtime > (ansible_date_time.epoch | int) - 3600

    - name: 'Search machineconfig manifest'
      ansible.builtin.find:
        path: "{{ appliance_upgrade_dir }}/"
        patterns: "^upgrade-machine-config-.*\\.yaml$"
        use_regex: true
      register: __upgrade_mc_file

    - name: 'Apply upgrade manifest'
      kubernetes.core.k8s:
        state: 'present'
        src: "{{ __upgrade_mc_file.files[0].path }}"
      ignore_errors: "{{ ansible_check_mode }}"
      when: __upgrade_mc_file.files[0].mtime > (ansible_date_time.epoch | int) - 3600
