---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: assisted-installer
data:
  DISABLED_HOST_VALIDATIONS: belongs-to-majority-group
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: assisted-service-config
spec:
  ingress:
    className: nginx
    assistedServiceHostname: "assisted-service.assisted-installer.com"
    imageServiceHostname: "assisted-image.assisted-installer.com"
  databaseStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "10Gi"
  filesystemStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "10Gi"
  imageStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "10Gi"
  osImages:
    - openshiftVersion: "4.17"
      cpuArchitecture: "x86_64"
      url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.17/4.17.0/rhcos-4.17.0-x86_64-live.x86_64.iso"
      version: "417.94.202408270355-0"
