---
galaxy_info:
  role_name: ocp_gitops
  namespace: mlorenzofr
  author: 'Manuel Lorenzo'
  description: 'Install and configure gitops operator on an Openshift Cluster'
  company: 'Red Hat'
  license: 'MIT'
  min_ansible_version: '2.12'
  platforms:
    - name: 'EL'
      versions:
        - '8'
        - '9'
  galaxy_tags: []
dependencies:
  - name: 'ocp_assisted_service'
    vars:
      ocp_acm_siteconfig: True
      ocp_assisted_service_config: {}
      ocp_assisted_service_op: 'acm'
    when: ocp_gitops_ztp
