---
- name: 'Reload systemd daemon'
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: 'systemd daemon-reload'

- name: 'Flush iptables rules'
  ansible.builtin.command:
    cmd: 'iptables -F'
  listen: 'flush iptables'

- name: 'Restart libvirtd service'
  ansible.builtin.service:
    name: 'libvirtd'
    state: 'restarted'
    enabled: true
  listen: 'svc restart libvirtd'

- name: 'Restart chronyd service'
  ansible.builtin.service:
    name: 'chronyd'
    state: 'restarted'
    enabled: true
  listen: 'svc restart chronyd'

- name: 'Restart squid service'
  ansible.builtin.service:
    name: 'squid'
    state: 'restarted'
    enabled: true
  listen: 'svc restart squid'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Restart ksushy service'
  ansible.builtin.service:
    name: 'ksushy'
    state: 'restarted'
    enabled: true
  listen: 'svc restart ksushy'
  ignore_errors: "{{ ansible_check_mode }}"
