---
# This playbook installs a lab with ACM running on an Openshift cluster
#
# Run it with:
#   ap labs/acm/acm.yaml

- name: 'Import compact playbook'
  ansible.builtin.import_playbook: ../base/compact.yml
  vars:
    lab_name: 'acm'
    lab_node_memory: 28000
    lab_node_disk_data: 60
    start_install: true

- name: 'Import ACM setup playbook'
  ansible.builtin.import_playbook: ../setup/acm.yaml
  vars:
    lab_name: 'acm'
