---
# This playbook installs a lab with ACM running on an Openshift cluster
#
# Run it with:
#   ap labs/acm/acm.yaml

- name: 'Import compact playbook'
  ansible.builtin.import_playbook: ../base/compact.yml
  vars:
    lab_name: 'acm'
    lab_node_memory: 28000
    lab_node_disk_data: 60
    start_install: true

- name: 'Import ACM setup playbook'
  ansible.builtin.import_playbook: ../setup/hive.yml
  vars:
    lab_name: 'acm'
    ocp_assisted_service_op: 'acm'
    ocp_baremetal_infras:
      - name: 'infra1'
        ns: 'hardware-inventory'
        pullsecret: "{{ lab_pull_secret }}"
        sshkey: "{{ lab_ssh_pubkey }}"
        ntp: ["{{ lab_node_network }}.1"]
        redfish: "{{ lab_node_network }}.1"
        inventory:
          - {'name': "{{ lab_name }}-worker-1", 'id': '51'}
          - {'name': "{{ lab_name }}-worker-2", 'id': '52'}
