---
# Run it with:
#   ap labs/acm/deploy.yaml

- name: 'Clean acm lab'
  ansible.builtin.import_playbook: ../../playbooks/jobs/clean-lab.yml
  vars:
    lab_name: 'acm'
  tags:
    - 'clean'
    - 'never'

- name: 'Import ABI playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  tags:
    - 'ocp'
  vars:
    lab_name: 'acm'
    lab_abi_ip: "{{ lab_node_network_base }}61"
    lab_api_ips: ["{{ lab_node_network_base }}100"]
    lab_ingress_ips: ["{{ lab_node_network_base }}101"]
    lab_node_memory: 28000
    lab_node_disk_data: 60
    lab_hosts:
      - {id: '61', role: 'master'}
      - {id: '62', role: 'master'}
      - {id: '63', role: 'master'}
    start_install: true

- name: 'Import ACM setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/acm.yaml
  tags:
    - 'postinst'
  vars:
    lab_name: 'acm'

    ocp_assisted_service_infraenvs:
      - name: 'spoke'
        ns: 'hive-sno'
        ntp: ["{{ lab_node_network_base }}1"]
        redfish: "{{ lab_node_network_base }}1"
        inventory:
          - {name: "{{ lab_name }}-bmh-1", id: '64'}
