---
- name: 'Create gitops cluster namespace'
  kubernetes.core.k8s:
    name: "{{ item.ns }}"
    api_version: v1
    kind: Namespace
    state: present

- name: 'Create gitops cluster pull-secret'
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: 'v1'
      kind: 'Secret'
      type: 'kubernetes.io/dockerconfigjson'
      metadata:
        name: "{{ item.pull_secret_name }}"
        namespace: "{{ item.ns }}"
      data:
        .dockerconfigjson: "{{ item.pull_secret | default(ocp_gitops_pull_secret) }}"

- name: 'Create secrets for BMC credentials'
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: 'v1'
      kind: 'Secret'
      type: 'Opaque'
      metadata:
        name: "{{ bmc.hostname }}-bmc-secret"
        namespace: "{{ item.ns }}"
      data:
        password: "{{ bmc.bmc_password | default(ocp_gitops_bmc_password) }}"
        username: "{{ bmc.bmc_username | default(ocp_gitops_bmc_username) }}"
  loop: "{{ item.nodes }}"
  loop_control:
    loop_var: bmc
    extended: true
