---
- name: 'Install Hive Operator'
  ansible.builtin.command:
    cmd: "/usr/local/bin/oc apply -f {{ ocp_hive_path }}/hive-subscription.yaml"
  when: ocp_hive_install
  listen: 'hive operator install'

- name: 'Waiting until the hive operator is installed'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc -n {{ ocp_hive_ns }} wait
      --for=jsonpath='{.status.state}'=AtLatestKnown
      subscription/hive --timeout=300s
  changed_when: false
  failed_when: false
  when: ocp_hive_install
  listen: 'hive operator install'

- name: 'Waiting until lvms-operator pods are ready'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc wait -n {{ ocp_lvms_ns }}
      -l control-plane=hive-operator
      --for=condition=Ready
      pods --timeout=300s
  changed_when: false
  failed_when: false
  when: ocp_hive_install
  listen: 'hive operator install'

- name: 'Apply custom ClusterImageSets'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc apply -f {{ ocp_hive_path }}/clusterimageset.yaml
  when: ocp_hive_install
  listen:
    - 'hive clusterimagesets'

- name: 'Apply hive clusters changes'
  ansible.builtin.command:
    cmd: >
      /usr/local/bin/oc apply -f {{ ocp_hive_path }}/hive
  when: ocp_hive_install
  listen:
    - 'hive cluster update'
