---
ocp_lvms_install: "{{ lab_install | default(false) }}"
ocp_lvms_ns: 'openshift-storage'
ocp_lvms_path: "{{ lab_configs }}"
ocp_lvms_source: 'redhat-operators'
ocp_lvms_clusters:
  - name: 'lv-data'
    ns: 'openshift-storage'
    classes:
      - name: 'vg1'
        default: True
        devices: ['/dev/vdb']
        node_role: 'worker'
