---
ocp_lvms_apply: "{{ ocp_apply | default(true) }}"
ocp_lvms_ns: 'openshift-storage'
ocp_lvms_path: "{{ lab_configs | default('/tmp') }}"
ocp_lvms_source: 'redhat-operators'
ocp_lvms_cluster_default_device: 'vdb'
ocp_lvms_cluster_default_role: 'worker'
ocp_lvms_clusters:
  - name: 'lv-data'
    ns: "{{ ocp_lvms_ns }}"
    classes:
      - name: 'vg1'
        default: True
        devices: ["/dev/{{ ocp_lvms_cluster_default_device }}"]
        node_role: "{{ ocp_lvms_cluster_default_role }}"
