---
- name: 'Prepare /opt/dnsmasq directory'
  ansible.builtin.file:
    path: '/opt/dnsmasq/include.d/'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: 'Ensure hosts.leases are present'
  ansible.builtin.file:
    path: '/opt/dnsmasq/hosts.leases'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'touch'
    access_time: 'preserve'
    modification_time: 'preserve'

- name: 'Configure SELinux for hosts.leases file'
  community.general.sefcontext:
    target: '/opt/dnsmasq/(.*)?\.leases'
    ftype: 'a'
    setype: 'dnsmasq_lease_t'
    state: present
  notify:
    - 'selinux dnsmasq'

- name: 'Configure SELinux for dnsmasq configuration files'
  community.general.sefcontext:
    target: "{{ item }}"
    ftype: 'a'
    setype: 'dnsmasq_etc_t'
    state: present
  loop:
    - '/opt/dnsmasq'
    - '/opt/dnsmasq/(.*)?\.conf'
    - '/opt/dnsmasq/include.d(/.*)?'
  notify:
    - 'selinux dnsmasq'

- name: 'Prepare dnsmasq-virt.service unit'
  ansible.builtin.template:
    src: 'dnsmasq/dnsmasq.unit.j2'
    dest: '/etc/systemd/system/dnsmasq-virt.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'systemd daemon-reload'
    - 'svc mask dnsmasq'
    - 'svc restart dnsmasq-virt'

- name: 'Configure dnsmasq-virt'
  ansible.builtin.template:
    src: 'dnsmasq/dnsmasq.conf.j2'
    dest: '/opt/dnsmasq/dnsmasq.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'svc restart dnsmasq-virt'

- name: 'Configure dnsmasq resolver'
  ansible.builtin.template:
    src: 'dnsmasq/upstream-resolv.conf.j2'
    dest: '/opt/dnsmasq/upstream-resolv.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'svc restart dnsmasq-virt'
...
