---
- name: 'Test if helm is present'
  ansible.builtin.stat:
    path: "/usr/local/bin/helm"
  register: __helm

- name: 'Download helm'
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-v{{ lab_host_helm_version }}-linux-amd64.tar.gz"
    include: ['linux-amd64/helm']
    remote_src: true
    dest: '/usr/local/bin/'
    owner: 'root'
    group: 'root'
    mode: '0755'
    extra_opts:
      - '--strip-components=1'
  when: not __helm.stat.exists
...
