---
- name: 'Enable kcli copr repository'
  community.general.copr:
    name: 'karmab/kcli'
    state: 'enabled'
    chroot: 'epel-8-x86_64'

- name: 'Install kcli package'
  ansible.builtin.package:
    name: 'kcli'
    state: 'present'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Install ksushy service'
  ansible.builtin.command:
    cmd: 'kcli create sushy-service --ssl --port 9000 --bootonce'
    creates: '/usr/lib/systemd/system/ksushy.service'
  notify:
    - 'systemd daemon-reload'
    - 'svc restart ksushy'

- name: 'Add ksushy overrides'
  ansible.builtin.template:
    src: 'ksushy.override.j2'
    dest: '/etc/systemd/system/ksushy.service.d/override.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'systemd daemon-reload'
    - 'svc restart ksushy'
...
