---
- name: 'Test if oc is present'
  ansible.builtin.stat:
    path: "/usr/local/bin/oc-{{ item }}"
  register: __oc

- name: 'Download oc'
  ansible.builtin.unarchive:
    src: "{{ lab_host_ocp_mirror }}/x86_64/clients/ocp/{{ item }}/openshift-client-linux-amd64-rhel8.tar.gz"
    include: ['oc']
    remote_src: true
    dest: '/tmp/'
  when: not __oc.stat.exists

- name: 'Test oc downloaded file'
  ansible.builtin.stat:
    path: '/tmp/oc'
  register: __tmp_oc

- name: 'Move oc to /usr/local/bin'
  ansible.builtin.copy:
    src: '/tmp/oc'
    dest: "/usr/local/bin/oc-{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0755'
    remote_src: true
  when: __tmp_oc.stat.exists

- name: 'Remove oc temporal file'
  ansible.builtin.file:
    path: '/tmp/oc'
    state: 'absent'

- name: 'Add oc alternative'
  community.general.alternatives:
    name: 'oc'
    link: '/usr/local/bin/oc'
    path: "/usr/local/bin/oc-{{ item }}"
    state: 'present'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Test if openshift-install is present'
  ansible.builtin.stat:
    path: "/usr/local/bin/openshift-install-{{ item }}"
  register: __openshift_install

- name: 'Download openshift-install'
  ansible.builtin.unarchive:
    src: "{{ lab_host_ocp_mirror }}/x86_64/clients/ocp/{{ item }}/openshift-install-linux.tar.gz"
    include: ['openshift-install']
    remote_src: true
    dest: '/tmp/'
  when: not __openshift_install.stat.exists

- name: 'Test openshift-install downloaded file'
  ansible.builtin.stat:
    path: '/tmp/openshift-install'
  register: __tmp_openshift_install

- name: 'Move openshift-install to /usr/local/bin'
  ansible.builtin.copy:
    src: '/tmp/openshift-install'
    dest: "/usr/local/bin/openshift-install-{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0755'
    remote_src: true
  when: __tmp_openshift_install.stat.exists

- name: 'Remove openshift-install temporal file'
  ansible.builtin.file:
    path: '/tmp/openshift-install'
    state: 'absent'

- name: 'Add openshift-install alternative'
  community.general.alternatives:
    name: 'openshift-install'
    link: '/usr/local/bin/openshift-install'
    path: "/usr/local/bin/openshift-install-{{ item }}"
    state: 'present'
  ignore_errors: "{{ ansible_check_mode }}"
...
