---
- name: 'Create dnsmasq snippet for the hosted cluster nodes'
  ansible.builtin.include_role:
    name: 'dnsmasq'
    tasks_from: 'extra_conf.yaml'
  vars:
    dnsmasq_conf_snippets:
      - {src: 'dnsmasq-hcp.j2', dest: "{{ ocp_hcp_lab_name }}-{{ item.name }}-cluster.conf"}
  tags: ['dnsmasq']

- name: 'Prepare hosted cluster environment'
  ansible.builtin.template:
    src: 'clusterenv.yaml.j2'
    dest: "{{ ocp_hcp_path }}/hcp/01-{{ item.name }}-env.yaml"
    mode: '0644'
  notify: 'hcp update'

- name: 'Prepare hosted cluster'
  ansible.builtin.template:
    src: 'cluster.yaml.j2'
    dest: "{{ ocp_hcp_path }}/hcp/02-{{ item.name }}.yaml"
    mode: '0644'
  notify: 'hcp update'
