---
apiVersion: v1
kind: Namespace
metadata:
  name: 'acm2'
  # labels:
  #  cluster.open-cluster-management.io/managedCluster: 'acm2'
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: 'acm2'
  labels:
    cloud: 'auto-detect'
    vendor: 'auto-detect'
spec:
  hubAcceptsClient: true
---
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: 'acm2'
type: Opaque
stringData:
  autoImportRetry: "5"
  kubeconfig: |-
    clusters:
    - cluster:
        certificate-authority-data: <redacted>
        server: https://api.acm2.local.lab:6443
      name: acm2
    contexts:
    - context:
        cluster: acm2
        user: admin
      name: admin
    current-context: admin
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: <redacted>
        client-key-data: <redacted>
