---
- name: 'Create LVM installation manifest'
  ansible.builtin.include_role:
    name: 'ocp_olm'
    tasks_from: 'subscription.yaml'
  loop:
    - operator_name: 'lvms-operator'
      subscription_name: 'lvms'
      ns: "{{ ocp_lvms_ns }}"
      monitoring: True
      privileged: True
      operator_group: 'openshift-storage-operatorgroup'
      source: "{{ ocp_lvms_source }}"
  tags: ['olm']

- name: 'Waiting for lvms-operator pods'
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        namespace: "{{ ocp_lvms_ns }}"
    label_selectors:
      - 'app.kubernetes.io/name=lvms-operator'
    wait: yes
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Create lvmclusters'
  ansible.builtin.include_tasks:
    file: 'lvmclusters.yaml'
  loop: "{{ ocp_lvms_clusters }}"
