---
apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: openshift-cluster-csi-drivers
stringData:
  # key: <PRISM-ELEMENT>:<PRISM-ELEMENT-PORT>:<USERNAME>:<PASSWORD>
  key: <redacted>:9440:<redacted>:<redacted>
---
apiVersion: v1
kind: Secret
metadata:
  name: ntnx-pc-secret
  namespace: openshift-cluster-csi-drivers
data:
  # key: <PRISM-CENTRAL>:<PRISM-CENTRAL-PORT>:<USERNAME>:<PASSWORD> base64 encoded
  key: <redacted>
