---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nutanixcsioperator
  namespace: openshift-cluster-csi-drivers
spec:
  installPlanApproval: Automatic
  name: nutanixcsioperator
  source: nutanix-csi-operator-beta
  sourceNamespace: openshift-marketplace
  startingCSV: nutanixcsioperator.v2.6.10
