---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: parted
rendezvousIP: 192.168.125.31
hosts:
  - hostname: parted-node-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:31
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:31
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: parted-node-2
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:32
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:32
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: parted-node-3
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:03:33
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:03:33
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
