---
# Run it with:
#   ap labs/neat/deploy.yaml

- name: 'Import ABI playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  vars:
    lab_name: 'neat'
    lab_node_memory: 32000
    lab_node_disk_data: 60
    start_install: true
    lab_abi_ip: "{{ lab_node_network_base }}65"
    lab_api_ips: ["{{ lab_node_network_base }}60"]
    lab_ingress_ips: ["{{ lab_node_network_base }}61"]
    lab_hosts:
      - {id: '65'}
      - {id: '66'}
      - {id: '67'}
  tags:
    - 'ocp'

- name: 'Import ACM setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/hcp.yaml
  vars:
    lab_name: 'neat'

    ocp_assisted_service_op: 'acm'
    ocp_assisted_service_config:
      ALLOW_CONVERGED_FLOW: '"false"'
      LOG_LEVEL: 'debug'
      ENABLE_KUBE_API: '"false"'
      AUTH_TYPE: 'none'
      OS_IMAGES: '[{"openshift_version":"4.15","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.15/4.15.0/rhcos-4.15.0-x86_64-live.x86_64.iso","version":"415.92.202402130021-0"}]'
      RELEASE_IMAGES: '[{"openshift_version":"4.15","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.15.20-x86_64","version":"4.15.20"}]'

    ocp_assisted_service_infraenvs:
      - name: 'infra1'
        ns: 'hardware-inventory'
        hypershift: true
        ntp: ["{{ lab_node_network_base }}1"]
        redfish: "{{ lab_node_network_base }}1"
        inventory:
          - {'name': "{{ lab_name }}-bmh-1", 'id': '68'}
          - {'name': "{{ lab_name }}-bmh-2", 'id': '69'}
          - {'name': "{{ lab_name }}-bmh-3", 'id': '70'}

    ocp_hcp_kubeapi_ips: ["{{ lab_node_network_base }}62-{{ lab_node_network_base }}64"]
  tags:
    - 'postinst'
    - 'acm'
