apiVersion: v1beta1
kind: ApplianceConfig
ocpRelease:
  version: 4.18.0
  channel: stable
  cpuArchitecture: x86_64
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
userCorePass: <redacted>
diskSizeGB: 150
stopLocalRegistry: True
