---
- name: 'Set watchAllNamespaces for provisioning'
  kubernetes.core.k8s:
    definition:
      apiVersion: 'metal3.io/v1alpha1'
      kind: 'Provisioning'
      metadata:
        name: 'provisioning-configuration'
      spec:
        watchAllNamespaces: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Create infrastructure configurations directory'
  ansible.builtin.file:
    path: "{{ ocp_baremetal_path }}/infra"
    mode: '0750'
    state: 'directory'

- name: 'Prepare infrastructures'
  ansible.builtin.include_tasks:
    file: 'infra.yml'
  loop: "{{ ocp_baremetal_infras }}"
